name: CI/CD Backend - Build and Push Docker Image

on:
  push:
    branches:
      - main
    tags:
      - 'v*.*.*'
    paths:
      - 'backend/**'

# Se elimina la sección 'env' global de IMAGE_NAME para evitar errores de sintaxis en el validador YAML.

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    # Definimos la URL de repositorio DENTRO del job.
    env:
      # CORRECCIÓN DE SINTAXIS: Usamos la función lower() de GitHub Actions 
      # para garantizar MINÚSCULAS en la URL, sin romper la validación YAML.
      GHCR_REPOSITORY: ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name | lower }}/backend-api

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.GHCR_REPOSITORY }}
          tags: |
            type=raw,value=latest,enable=${{ github.ref == format('refs/heads/{0}', 'main') }} 
            type=semver,pattern=v{{version}} 
            type=sha,prefix=sha-

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./backend/Dockerfile 
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha 
          cache-to: type=gha,mode=max